---
- hosts: localhost
  become: no
  vars:
    user: pyconde
    workdir: "/Users/{{ user }}/Documents/scripts"
    venv_dir: "{{ workdir }}/venv"
    code_checkout: "{{ workdir }}/code"
    code_desktop: "/Users/{{ user }}/Desktop/code"
    product_dir: "PyCharm2017.3"
  tasks:
    - name: Get the code from GitHub
      git:
        repo: https://github.com/ErnstHaagsman/selenium_experiment.git
        dest: "{{ code_checkout }}"
        update: yes
        version: bugs
        force: yes

    - name: Update setuptools, and devpi
      pip:
        name:
          - setuptools
          - devpi-server
        state: latest
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python3

    - name: Initialize devpi
      command: "{{ venv_dir }}/bin/devpi-server --init"
      args:
        creates: "/Users/{{ user }}/.devpi"

    - name: Start devpi
      command: "{{ venv_dir }}/bin/devpi-server --start"

    - name: Make sure we have a pip config directory
      file:
        path: "/Users/{{ user }}/Library/Application Support/pip"
        state: directory

    - name: Copy pip config
      copy:
        src: files/pip.conf
        dest: "/Users/{{ user }}/Library/Application Support/pip/pip.conf"

    - name: Preload Python packages needed during the test
      pip:
        name:
          - selenium
        state: latest
        virtualenv: "/tmp/test_venv_temporary"
        virtualenv_python: python3

    - name: Make sure recordings directory exists
      file:
        name: "{{ workdir }}/recordings"
        state: directory
