---
- hosts: localhost
  become: no
  vars:
    user: pyconde
    workdir: "/Users/{{ user }}/Documents/scripts"
    code_checkout: "{{ workdir }}/code"
    code_desktop: "/Users/{{ user }}/Desktop/code"
    product_dir: "PyCharm2017.3"
  tasks:
    - name: Kill PyCharm
      command: killall pycharm
      ignore_errors: yes

    - name: Kill Firefox
      command: killall firefox
      ignore_errors: yes

    - name: Pause to wait until PyCharm is (likely) killed
      pause:
        seconds: 5

    - name: Get the code from GitHub
      git:
        repo: https://github.com/ErnstHaagsman/selenium_experiment.git
        dest: "{{ code_checkout }}"
        update: no
        version: bugs
        force: yes

    - name: Remove previous version, if applicable
      file:
        path: "{{ code_desktop }}"
        state: absent

    - name: Create code directory on desktop
      file:
        path: "{{ code_desktop }}"
        state: directory

    - name: Copy a version of the code to the desktop
      command: "cp -R {{code_checkout}}/ {{code_desktop}}"

    - name: Remove .git directory
      file:
        path: "{{ code_desktop }}/.git"
        state: absent

    - name: Add Geckodriver
      copy:
        src: files/geckodriver
        dest: "{{ code_desktop }}/geckodriver"
        mode: 0755

    - name: Remove PycharmProjects
      file:
        path: "/Users/{{ user }}/PycharmProjects"
        state: absent

    - name: Remove IDE plugins
      file:
        path: "/Users/{{ user }}/Library/Application Support/{{ product_dir }}"
        state: absent

    - name: Remove IDE settings
      file:
        path: "/Users/{{ user }}/Library/Preferences/{{ product_dir }}"
        state: absent

    - name: Remove IDE logs
      file:
        path: "/Users/{{ user }}/Logs/{{ product_dir }}"
        state: absent

    - name: Remove IDE caches
      file:
        path: "/Users/{{ user }}/Library/Caches/{{ product_dir }}"
        state: absent

    - name: Copy IDE settings
      copy:
        src: "files/{{ product_dir }}"
        dest: "/Users/{{ user }}/Library/Preferences/{{ product_dir }}"

    - name: Copy instructions
      copy:
        src: files/Instructions.pdf
        dest: "/Users/{{ user }}/Desktop/Instructions.pdf"

    - name: Copy start
      copy:
        src: files/start.command
        dest: "/Users/{{ user }}/Desktop/Start.command"
        mode: 0755

    - name: Copy end
      copy:
        src: files/end.command
        dest: "/Users/{{ user }}/Desktop/End.command"
        mode: 0755

    - name: Start devpi
      command: "{{ venv_dir }}/bin/devpi-server --start"

    - name: Ensure Vagrant is up
      command: vagrant up
      args:
        chdir: "/Users/{{ user }}/Documents/scripts/reddit/"
